const a = {
  24: "http://www.sportslogos.net/logos/list_by_team/1736/Anaheim_Ducks/",
  53: "http://www.sportslogos.net/logos/list_by_team/5263/Arizona_Coyotes/",
  6: "http://www.sportslogos.net/logos/list_by_team/3/Boston_Bruins/",
  7: "http://www.sportslogos.net/logos/list_by_team/4/Buffalo_Sabres/",
  20: "http://www.sportslogos.net/logos/list_by_team/5/Calgary_Flames/",
  12: "http://www.sportslogos.net/logos/list_by_team/6/Carolina_Hurricanes/",
  16: "http://www.sportslogos.net/logos/list_by_team/7/Chicago_Blackhawks/",
  21: "http://www.sportslogos.net/logos/list_by_team/8/Colorado_Avalanche/",
  29: "http://www.sportslogos.net/logos/list_by_team/9/Columbus_Blue_Jackets/",
  25: "http://www.sportslogos.net/logos/list_by_team/10/Dallas_Stars/",
  17: "http://www.sportslogos.net/logos/list_by_team/11/Detroit_Red_Wings/",
  22: "http://www.sportslogos.net/logos/list_by_team/12/Edmonton_Oilers/",
  13: "http://www.sportslogos.net/logos/list_by_team/13/Florida_Panthers/",
  26: "http://www.sportslogos.net/logos/list_by_team/14/Los_Angeles_Kings/",
  30: "http://www.sportslogos.net/logos/list_by_team/15/Minnesota_Wild/",
  8: "http://www.sportslogos.net/logos/list_by_team/16/Montreal_Canadiens/",
  18: "http://www.sportslogos.net/logos/list_by_team/17/Nashville_Predators/",
  1: "http://www.sportslogos.net/logos/list_by_team/18/New_Jersey_Devils/",
  2: "http://www.sportslogos.net/logos/list_by_team/19/New_York_Islanders/",
  3: "http://www.sportslogos.net/logos/list_by_team/20/New_York_Rangers/",
  9: "http://www.sportslogos.net/logos/list_by_team/21/Ottawa_Senators/",
  4: "http://www.sportslogos.net/logos/list_by_team/22/Philadelphia_Flyers/",
  5: "http://www.sportslogos.net/logos/list_by_team/24/Pittsburgh_Penguins/",
  28: "http://www.sportslogos.net/logos/list_by_team/26/San_Jose_Sharks/",
  19: "http://www.sportslogos.net/logos/list_by_team/25/St._Louis_Blues/",
  14: "http://www.sportslogos.net/logos/list_by_team/27/Tampa_Bay_Lightning/",
  10: "http://www.sportslogos.net/logos/list_by_team/28/Toronto_Maple_Leafs/",
  23: "http://www.sportslogos.net/logos/list_by_team/29/Vancouver_Canucks/",
  54: "http://www.sportslogos.net/logos/list_by_team/6114/Vegas_Golden_Knights/",
  15: "http://www.sportslogos.net/logos/list_by_team/30/Washington_Capitals/",
  52: "http://www.sportslogos.net/logos/list_by_team/3050/Winnipeg_Jets/}"
};

export default a;
